version: '3.7'

services:
  # web:
  #   build: './web'
  #   depends_on:
  #     - server
  #   container_name: 'laboremus_dc'
  #   image: 'olilidaniel48/laboremus/frontend'
  #   volumes:
  #     - ./web:/app
  #   ports:
  #     - 80:3000
  server:
    build: './server'
    container_name: 'backend'
    image: 'olilidaniel48/laboremus/backend'
    volumes:
      - ./server:/server
    ports:
      - 3000:3000
    restart: always